network_server:
  object_detect_service_name: object_detect_service
  network_cloud_service_name: network_cloud_service
  network_semantic_service_name: network_semantic_service
  yolov3:
    checkpoints: /home/ericlab/Downloads/yolov3_real_final.pth
    config_path: /home/ericlab/tsuchida/ros_package/study_ws/src/denso_estimation/network/src/network/object_detection/yolov3/config/yolov3_denso.yaml
  semantic_pointnet:
    class_num: 2
    checkpoints: /home/ericlab/tsuchida/2022_11/checkpoints/SemSeg/semantic_11_23/180.pth