acc_estimation_main:
  # hdf5_open_file_path: /home/ericlab/tsuchida/test_data/acc_real_latest.hdf5
  hdf5_open_file_path: /home/ericlab/tsuchida/test_data/real_t_pipe.hdf5
  estimation_name: propose
  object_detect_mode: ssd
  # object_detect_checkpoint_path: /home/ericlab/tsuchida/2022_12/checkpoints/SSD/full_randomize/HV8/model_005000.pth
  # object_detect_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/SSD/HV8/full_randomizer_3000/model_005000.pth
  object_detect_checkpoint_path: /home/ericlab/tsuchida/2022_12/checkpoints/SSD/full_randomize/t_pipe/model_final.pth
  semantic_class_num: 2
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/sensor_b_box_2000_noize/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2022_12/checkpoints/Semseg/sensor_b_box_para_kai_final/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2022_12/checkpoints/Semseg/no_sensor_kai/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2022_12/checkpoints/Semseg/no_b_box/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/sensor_b_box_3000_noize_not_board/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/sensor_b_box_2000_max_noize/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/sensor_b_box_2000_noize_max_improve/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/sensor_b_box_2000_noize_improve_box/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/sensor_b_box_2000_super_noize_improve/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/sensor_b_box_7000_improve/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/sensor_b_box_3000_super_noize/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/sensor_b_box_2000_super_noize_kai/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/3000_super_noize/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/4000_propose/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/5000_propose/latest.pth
  # semantic_checkpoint_path: /home/ericlab/tsuchida/2023_01/checkpoints/Semseg/HV8/1000_propose/latest.pth
  semantic_checkpoint_path: /home/ericlab/tsuchida/2023_02/checkpoints/Semseg/t_pipe/3000_propose/latest.pth

decide_object_position:
  sensor_name: phoxi_camera
  sensor_angle_max: 0.087
  sensor_angle_min: 0.087
  distance: 1.1
  z_position: 0.003
  box_height: 0.01
  box_name: denso_box
  object_height: 0.15
  radious: 0.05

data_transform_pkg:
  f_scale: 0.968
  cx_scale: 1.02
  cy_scale: 1.0
  
data_3D_to_2D:
  radious_x: 0.05
  radious_y: 0.05
